spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.c0ny6qzu64ar.ap-northeast-1.rds.amazonaws.com:3306/mblog?user=admin&password=bc123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# 日志配置
# logback有5种级别，分别是TRACE < DEBUG < INFO < WARN < ERROR
# OFF 关闭所有日志， ALL 开启所有日志
logging:
  level:
    root: info
    me.bxbc: info
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB
  file:
    name: log/mlog-dev.log



